### ISSUE TITLE
Provide Snippet for Batch Apex Class

### ISSUE THREAD

**Issue by mailtoharshit** [mailtoharshit/Weave#13]
@npathuri0531 - Can you please provide batch apex class snippet and make sure you submit it to tag v.1.0.6 (latest tag).

**Comment by mailtoharshit** [comment]
@vikramanisetty - Please design a template code for Batch Apex Class with proper commenting scheme. We will do code review and pull request from here.

**Comment by npathuri0531** [comment]
global with sharing class SampleBatchClass implements Database.Batchable<sObject>,Database.Stateful,Schedulable{

    /**
      * Member variables that can be reused in entire batch class  
    **/
    private Boolean isErroroccurred = false;

    /**
      * Constructor for doing the work that is common to entire batch class  
    **/
    public SampleBatchClass(){

    } 
    
    /**
      * Start method to gather records to be processed in the batch class  
    **/
    global  Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'Select Id,Name,ALL_YOUR_NEEDED_FIELDS From YOUR_SOBJECT';
        return Database.getQueryLocator(query);
    }

    /**
      * Execute method to process records to be processed in the batch class. Handler will process the records. 
    **/    
    global void execute(Database.BatchableContext BC, List < sObject > scope) {
        SampleBatchClassHandler.ProcessBatch(List<YOUR_SOBJECT> (scope));
    }

    /**
      * Finish method to notify the team for any errors in the batch. 
    **/ 

    global void finish(Database.BatchableContext BC) {
        if(isErroroccurred){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new List<String>{'TO_EMAIL'});
            mail.setReplyTo('noreply@Intsurg.com');
            mail.setSenderDisplayName('Apex Batch Processing Failures');
            mail.setSubject(' SampleBatchClass Batch Processing failures');
            mail.setHTMLBody('SampleBatchClass failed. Please check Apex Log for errors.');
            Messaging.sendEmail(new Messaging.Singleemailmessage [] {mail});
        } 
    }

    /**
      * Execute method that allows for easy scheduling of the same batch class
    **/

    global void execute(SchedulableContext sc) {
        id batchId = Database.executeBatch(new SampleBatchClass(),10 );        
    }
    
}

**Comment by mailtoharshit** [comment]
@npathuri0531  - Did you verified functionality - can you provide test class for this. Let close this, when we have test class and working code, I'll generate template out of it !

**Comment by npathuri0531** [comment]
@isTest
public with sharing class RunRateSnapShotCaptureByHospital_Tests{
    /**
     * private static variables. Include SObject variables, collections or any variables needed for test class
    **/
    private static User adminUser1;
    
    static{
        // create admin user and assert it
        adminUser1 = SFA_TestUtil.createUser(SFA_Constants.PROFILE_SYS_ADMIN, true);
        system.assertNotEquals(null, adminUser1.Id);

        system.runAs(adminUser1){
            createTestData();
        }    

    }

    private static void createTestData(){
        /**
         * Create Test Data and assert it
        **/
    }

        /**
         * Test methods to test the functionality. Create multiple methods to test various functionality needs
        **/
    private static testMethod void TEST_METHOD1(){
        Test.startTest();
            system.runAs(adminUser1){
                SampleBatchClass b = new SampleBatchClass();
                Database.executebatch(b);
            }
        Test.stoptest();    
    }


    private static testMethod void TEST_METHOD2(){
        Test.startTest();
            system.runAs(adminUser1){
                string CRON_EXP = '0 0 0 15 3 ? 2022';
                SampleBatchClass scheduleBatch = new SampleBatchClass();
                //String jobId = System.schedule('Schedule Batch', CRON_EXP , scheduleBatch); 
                String jobId = System.scheduleBatch(scheduleBatch, 'Schedule Batch', 0, 500);
                CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
                  // Verify the expressions are the same
                  System.assertNotEquals(null, ct);
            }
        Test.stopTest();    
    }    

}
